language: node_js
node_js:
  - "5"
  - "4"
  - "4.4.4"

# Not compatible with older versions because some dependencies
# use yield/unyield, etc

# This needed for nodegit:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
